### ISSUE TITLE
stuck at await browser.NewPageAsync()

### ISSUE THREAD

**Issue by MussaratAziz** [hardkoded/puppeteer-sharp#1150] opened 2019-05-29 14:48 UTC
I am just trying to create a simple console app to generate PDF file but program doesn't execute after that line  `var page = await browser.NewPageAsync();` also i am not getting any exception as program is just stuck. Any help much appreciated. 
console app code: **Using .NET Core 2.2, PuppeteerSharp 1.17.1, C# version 7.1**
 ```
class Program
    {
        public static async Task Main(string[] args)
        {
            await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions { Headless = true });
            var page = await browser.NewPageAsync();
            PdfOptions pdfOptions = new PdfOptions();
            pdfOptions.PreferCSSPageSize = true;
            await page.GoToAsync("http://www.google.com", WaitUntilNavigation.Load);
            await page.PdfAsync(Path.Combine(Directory.GetCurrentDirectory(), "google.pdf"), pdfOptions);
        }
      
    }
```

**Comment by kblok** [comment] 2019-05-29 14:51
`await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);` might take a while. Did you leave it running for a few minutes?

**Comment by kblok** [comment] 2019-05-29 14:58
If you go to the bin folder, do you see a `.local-chromium` folder with Chromium unzipped?

**Comment by MussaratAziz** [comment] 2019-05-29 15:00
Yes its unzipped

**Comment by kblok** [comment] 2019-05-29 15:10
Your code worked perfectly on my side. Can you debug it and see here is getting stuck?

**Comment by MussaratAziz** [comment] 2019-05-29 15:14
i am trying to debug but when i press **F10** after that line mentioned above its just get stuck and i dont get and exception or error. Thats why i am bit confused and cant work out why ?

**Comment by DvlopRyanSpears** [comment] 2019-06-01 09:05
@MussaratAziz  Hi,I meet the same problem as you, But there is another way to control Chrome.
` var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true,
               ExecutablePath = Arstrox.HAL.PathResouce.CHROME_EXECUTABLE_PATH

            });`
ExcutablePath is the path of Chrome.exe installed on your computer.

**Comment by kblok** [comment] 2019-06-02 23:03
Do you still need help here @MussaratAziz ?

**Comment by kblok** [comment] 2019-06-07 11:20
Closed due to inactivity. Feel free to reopen it if needed.

**Comment by MussaratAziz** [comment] 2019-07-16 12:30
still await browser.NewPageAsync() stuck on this. I just dont know what i am doing wrong.

```
var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true,
                ExecutablePath = @"location of chrome.exe on my pc"

            });
            var page = await browser.NewPageAsync();
            PdfOptions pdfOptions = new PdfOptions();
            pdfOptions.PreferCSSPageSize = true;
            await page.GoToAsync("http://www.google.com", WaitUntilNavigation.Load);
            await page.PdfAsync(Path.Combine(Directory.GetCurrentDirectory(), "google.pdf"), pdfOptions);
```

**Comment by kblok** [comment] 2019-07-16 12:32
Can you post the log?
[see this article](https://github.com/kblok/puppeteer-sharp/blob/master/docfx_project/examples/LodCDP.md)

**Comment by MussaratAziz** [comment] 2019-07-16 12:54
2019-07-16T13:52:51.6878377+01:00  [VRB] Send ► 1 Method "Target.setDiscoverTargets" Params TargetSetDiscoverTargetsRequest { Discover: True } (c80f6283)
2019-07-16T13:52:51.8298410+01:00  [VRB] ◀ Receive "{\"method\":\"Target.targetCreated\",\"params\":{\"targetInfo\":{\"targetId\":\"72B533DDDE88541D66064BAECA218B4B\",\"type\":\"page\",\"title\":\"\",\"url\":\"about:blank\",\"attached\":false,\"browserContextId\":\"CBF200E2FB8F4225DB521561CADC330A\"}}}" (00f0de6d)
2019-07-16T13:52:51.8698431+01:00  [VRB] ◀ Receive "{\"method\":\"Target.targetCreated\",\"params\":{\"targetInfo\":{\"targetId\":\"9a115d08-4a62-4a44-a903-a55a06a1336a\",\"type\":\"browser\",\"title\":\"\",\"url\":\"\",\"attached\":true}}}" (00f0de6d)
2019-07-16T13:52:51.8698431+01:00  [VRB] ◀ Receive "{\"method\":\"Target.targetCreated\",\"params\":{\"targetInfo\":{\"targetId\":\"a739e940-264d-42f4-b3b5-3ffa687bc190\",\"type\":\"browser\",\"title\":\"\",\"url\":\"\",\"attached\":false}}}" (00f0de6d)
2019-07-16T13:52:51.8768411+01:00  [VRB] ◀ Receive "{\"id\":1,\"result\":{}}" (00f0de6d)
2019-07-16T13:52:54.6712609+01:00  [VRB] Send ► 2 Method "Target.createTarget" Params TargetCreateTargetRequest { Url: "about:blank", BrowserContextId: null } (c80f6283)
2019-07-16T13:52:54.6932545+01:00  [VRB] ◀ Receive "{\"method\":\"Target.targetCreated\",\"params\":{\"targetInfo\":{\"targetId\":\"9A362ED926C00F4C58CDF37EFD6A44F0\",\"type\":\"page\",\"title\":\"\",\"url\":\"\",\"attached\":false,\"browserContextId\":\"CBF200E2FB8F4225DB521561CADC330A\"}}}" (00f0de6d)
2019-07-16T13:52:54.6952583+01:00  [VRB] ◀ Receive "{\"id\":2,\"result\":{\"targetId\":\"9A362ED926C00F4C58CDF37EFD6A44F0\"}}" (00f0de6d)
2019-07-16T13:52:54.6962582+01:00  [VRB] ◀ Receive "{\"method\":\"Target.targetCrashed\",\"params\":{\"targetId\":\"9A362ED926C00F4C58CDF37EFD6A44F0\",\"status\":\"failed to launch\",\"errorCode\":18}}" (00f0de6d)

**Comment by kblok** [comment] 2019-07-16 12:55
Which version of Chrome are you trying to use?

**Comment by MussaratAziz** [comment] 2019-07-16 12:59
Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by kblok** [comment] 2019-07-16 13:00
You should use at least 76.0.3803.0 with Puppeteer 1.17

**Comment by MussaratAziz** [comment] 2019-07-16 13:12
76.0.3803.0 now using but still the same issue

**Comment by MussaratAziz** [comment] 2019-07-16 13:13
2019-07-16T14:12:52.9420197+01:00  [VRB] Send ► 1 Method "Target.setDiscoverTargets" Params TargetSetDiscoverTargetsRequest { Discover: True } (c80f6283)
2019-07-16T14:12:53.0900149+01:00  [VRB] ◀ Receive "{\"method\":\"Target.targetCreated\",\"params\":{\"targetInfo\":{\"targetId\":\"07D17B4B253F285EED99D1201ECD00B5\",\"type\":\"page\",\"title\":\"\",\"url\":\"about:blank\",\"attached\":false,\"browserContextId\":\"D2FD814398CBF621C611CFBD3DE3746A\"}}}" (00f0de6d)
2019-07-16T14:12:53.1310168+01:00  [VRB] ◀ Receive "{\"method\":\"Target.targetCreated\",\"params\":{\"targetInfo\":{\"targetId\":\"23ca4a27-25a4-4a73-b188-7affad3b0791\",\"type\":\"browser\",\"title\":\"\",\"url\":\"\",\"attached\":false}}}" (00f0de6d)
2019-07-16T14:12:53.1310168+01:00  [VRB] ◀ Receive "{\"method\":\"Target.targetCreated\",\"params\":{\"targetInfo\":{\"targetId\":\"bdbe313a-1a29-45cf-ada8-9a84745a6d27\",\"type\":\"browser\",\"title\":\"\",\"url\":\"\",\"attached\":true}}}" (00f0de6d)
2019-07-16T14:12:53.1370191+01:00  [VRB] ◀ Receive "{\"id\":1,\"result\":{}}" (00f0de6d)
2019-07-16T14:12:54.9400610+01:00  [VRB] Send ► 2 Method "Target.createTarget" Params TargetCreateTargetRequest { Url: "about:blank", BrowserContextId: null } (c80f6283)
2019-07-16T14:12:54.9490647+01:00  [VRB] ◀ Receive "{\"method\":\"Target.targetCreated\",\"params\":{\"targetInfo\":{\"targetId\":\"3CEFE540BB86329B05E9A8EF9AE72344\",\"type\":\"page\",\"title\":\"\",\"url\":\"\",\"attached\":false,\"browserContextId\":\"D2FD814398CBF621C611CFBD3DE3746A\"}}}" (00f0de6d)
2019-07-16T14:12:54.9530619+01:00  [VRB] ◀ Receive "{\"id\":2,\"result\":{\"targetId\":\"3CEFE540BB86329B05E9A8EF9AE72344\"}}" (00f0de6d)
2019-07-16T14:12:54.9670630+01:00  [VRB] ◀ Receive "{\"method\":\"Target.targetCrashed\",\"params\":{\"targetId\":\"3CEFE540BB86329B05E9A8EF9AE72344\",\"status\":\"failed to launch\",\"errorCode\":18}}" (00f0de6d)

**Comment by kblok** [comment] 2019-07-16 13:25
Chrome is crashing with error code 18. Could you try downloading chromium with `BrowserFetcher`?

**Comment by MussaratAziz** [comment] 2019-07-16 15:07
Sure i did that but still stuck on this as well.

**Comment by junyu422** [comment] 2019-08-06 02:13
I got the same problem

But I installed windows in mac pro

When the project has been put into the mac file path, but it happened again. So my solution is that put the project into the windows file path.

**Comment by NathanielACollier** [comment] 2019-08-19 16:59
I had this same problem, on windows, and was able to get it to work by doing this below.  If I didn't specify a path for BrowserFetcherOptions and then give that ExecutablePath to LaunchOptions the code would get to NewPageAsync and then get stuck calling NewPageAsync.

```c#
	var info = await new BrowserFetcher(new BrowserFetcherOptions
	{
		Path = @"C:\temp\2019-08-19-chromium"
	}).DownloadAsync(BrowserFetcher.DefaultRevision);
	var browser = await Puppeteer.LaunchAsync(new LaunchOptions{
		Headless = true
		,ExecutablePath = info.ExecutablePath
	});
	var page = await browser.NewPageAsync();
	await page.SetContentAsync("<div>Hello World!</div>");
	var resultHTML = await page.GetContentAsync();
```

**Comment by Inurias** [comment] 2019-08-23 09:53
> 
> 
> I had this same problem, on windows, and was able to get it to work by doing this below. If I didn't specify a path for BrowserFetcherOptions and then give that ExecutablePath to LaunchOptions the code would get to NewPageAsync and then get stuck calling NewPageAsync.
> 
> ```cs
> 	var info = await new BrowserFetcher(new BrowserFetcherOptions
> 	{
> 		Path = @"C:\temp\2019-08-19-chromium"
> 	}).DownloadAsync(BrowserFetcher.DefaultRevision);
> 	var browser = await Puppeteer.LaunchAsync(new LaunchOptions{
> 		Headless = true
> 		,ExecutablePath = info.ExecutablePath
> 	});
> 	var page = await browser.NewPageAsync();
> 	await page.SetContentAsync("<div>Hello World!</div>");
> 	var resultHTML = await page.GetContentAsync();
> ```

I have the same problem, also on windows. Sadly, your solution did not work for me.

**Comment by Inurias** [comment] 2019-08-24 14:52
> 
> 
> > I had this same problem, on windows, and was able to get it to work by doing this below. If I didn't specify a path for BrowserFetcherOptions and then give that ExecutablePath to LaunchOptions the code would get to NewPageAsync and then get stuck calling NewPageAsync.
> > ```cs
> > 	var info = await new BrowserFetcher(new BrowserFetcherOptions
> > 	{
> > 		Path = @"C:\temp\2019-08-19-chromium"
> > 	}).DownloadAsync(BrowserFetcher.DefaultRevision);
> > 	var browser = await Puppeteer.LaunchAsync(new LaunchOptions{
> > 		Headless = true
> > 		,ExecutablePath = info.ExecutablePath
> > 	});
> > 	var page = await browser.NewPageAsync();
> > 	await page.SetContentAsync("<div>Hello World!</div>");
> > 	var resultHTML = await page.GetContentAsync();
> > ```
> 
> I have the same problem, also on windows. Sadly, your solution did not work for me.

Although this is strongly discouraged on the [puppeteer troubleshooting guide](https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#setting-up-chrome-linux-sandbox), I managed to get it to work by launching with the "--no-sandbox" and "--disable-setuid-sandbox" arguments.
In my case, it should not be a problem since I only access local and static content in a controlled environment.

**Comment by kblok** [comment] 2019-09-04 11:04
@MussaratAziz @Inurias @junyu422 @NathanielACollier anything you want me to check?
All the comments seem to be deployment issues.

**Comment by StegBrind** [comment] 2019-09-17 10:59
**Puppeteer version**: 1.19.0
**Chromium version**: 77.0.3844.0

Hello everyone. I guess I have a similar problem. When I call await browser.NewPageAsync() in MainAsync(), then _Browser.NewPageAsync() will be called as expected, but when I call it in another static method it stucks. My code:
 ```
partial class Program
    {
        static Browser _Browser;

        static async Task StartBrowser()
        {
            Browser = await Puppeteer.LaunchAsync
               (
                   new LaunchOptions
                   {
                       Headless = true,
                       ExecutablePath = "Chromium\\chrome.exe"
                   }
               );
            Console.WriteLine("Browser launched");
        }

        static void StartScraping(int threads)
        {
            Task.WaitAll(
            Enumerable.Range(0, threads)
            .Select(async ThreadNumber =>
            {
                try
                {
                    Console.WriteLine("Thread #" + ThreadNumber + " started");
                    Page p = await Browser.NewPageAsync(); //stucks here
                    await p.GoToAsync("https://www.google.com");
                    Console.WriteLine("Content:\n" + await p.GetContentAsync());
                }
                catch (Exception e)
                {
                    Console.WriteLine("Thread #" + ThreadNumber + " failed. " + e);
                    throw;
                }
            }).ToArray());
        }

        static async Task MainAsync()
        {
            await StartBrowser();
            StartScraping(1);
        }

        static void Main(string[] args)
        {
            MainAsync().GetAwaiter().GetResult();
        }
    }
```

**Comment by wushuyi** [comment] 2019-09-27 17:29
``` c#
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                ExecutablePath = @".\chrome.exe",
                Headless = true
            });

            Console.WriteLine(await browser.GetVersionAsync());
            Console.WriteLine(await browser.GetUserAgentAsync());

            Page page = await browser.NewPageAsync();

            Console.WriteLine("end ...");
```

Version and UserAgent ok 
but stuck at await browser.NewPageAsync()

**Comment by wushuyi** [comment] 2019-09-27 17:30
but if LaunchOptions Headless = false it work

**Comment by StegBrind** [comment] 2019-09-28 08:09
I've solved my problem by using BrowserContext.
```
BrowserContext browser = _Browser.DefaultContext;
Page p = await browser.NewPageAsync();
```

**Comment by PccCodesix** [comment] 2019-10-11 03:41
Does anyone here solve this problem?  stuck at browser.NewPageAsync()

**Comment by KevinYeti** [comment] 2019-10-14 15:53
stuck at browser.NewPageAsync() too.

**Comment by KevinYeti** [comment] 2019-10-14 16:22
update:
I tried to open VS by administrator mode which works fine to me.

**Comment by PccCodesix** [comment] 2019-10-15 01:39
> update:
> I tried to open VS by administrator mode which works fine to me.

 Are you using Headless mode？
 VS in  administrator mode,I use  headless mode still stuck at browser.NewPageAsync() .
Can I see how you use it?

**Comment by KevinYeti** [comment] 2019-10-15 15:27
> > update:
> > I tried to open VS by administrator mode which works fine to me.
> 
> Are you using Headless mode？
> VS in administrator mode,I use headless mode still stuck at browser.NewPageAsync() .
> Can I see how you use it?

here is my code. 

```csharp
        private static async Task get()
        {
            await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true
            });
            var page = await browser.NewPageAsync();
            await page.GoToAsync("http://www.google.com/");
            var options = new ScreenshotOptions();
            options.FullPage = true;
            options.Quality = 100;
            options.Type = ScreenshotType.Jpeg;
            await page.ScreenshotAsync("c://1.jpg", options);
        }
```

**Comment by maurommx** [comment] 2019-11-22 13:04
I am using a translator,

I had the same problem, it worked on one network, but on another it didn't work, I could only make it work when

`Browser browser = await Puppeteer.LaunchAsync(new LaunchOptions
{
   Headless = true,

 IgnoreHTTPSErrors = true,
    Args = new[] {
    "--no-sandbox",
    "--disable-infobars",
    "--disable-setuid-sandbox",
    "--ignore-ICertificatePolicy-errors",
    },
});`

but I think it was the "--no-sandbox" option that solved it.
Was having the same problem on windows 7, I will test if with this option also works.

**Comment by natancd** [comment] 2020-09-02 14:40
Was anyone able to get a proper solution? I have the exact same issue.

**Comment by Robsando** [comment] 2020-10-07 18:07
Hi I had similar issue. 
In my case remove "using" wrapping helped.
Having await Puppeteer.LaunchAsync in using hangs.

> Was anyone able to get a proper solution? I have the exact same issue and none of the suggestions worked for me.
> The only difference is that I get stuck at this point:
> 
> ```
> using (Browser browser = await Puppeteer.LaunchAsync(new LaunchOptions
>                 {
>                     Headless = true,
>                     IgnoreHTTPSErrors = true,
>                     Devtools = false,
>                     Args = new[] { //regardless, but usually with disable-web-security and -no-sandbox }
>                 }))
> ```

**Comment by verybox0** [comment] 2020-10-16 08:23
Below is code which works for me:
```
            await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true,
                IgnoreHTTPSErrors = true,
                Args = new[] {
                    "--no-sandbox",
                    "--disable-infobars",
                    "--disable-setuid-sandbox",
                    "--ignore-ICertificatePolicy-errors",
                    },
            });
            var page = await browser.NewPageAsync();
```
**Before, without "IgnoreHTTPSErrors" and "Args", I am stuck too.**

**Comment by RakeshYadvanshi** [comment] 2020-11-10 05:56
Hi Everyone, 

if anyone still facing issues. 
I have sorted this issue by adding ConfigureAwait(false)

var browser = await Puppeteer.LaunchAsync(new LaunchOptions { Headless = true }).**ConfigureAwait(false)**;
var page = await browser.NewPageAsync().**ConfigureAwait(false)**;

where ever it stuck try to add **ConfigureAwait(false)** for async method only

**Comment by Androbin** [comment] 2021-02-05 20:02
I have the same issue but with `target.PageAsync()` (called from within `browser.TargetCreated`).
The issue happens randomly and I can't reproduce it perfectly reliably. I suspect there is a race condition with `Target.PageTask`

**Comment by Androbin** [comment] 2021-02-05 21:57
This seems to be enough to reproduce the issue, although it too is flaky:
```
var browser = Puppeteer.LaunchAsync(...);
var target = browser.Targets().Where(target => target.Type == TargetType.Page).First();
await target.PageAsync();
```

**Comment by Androbin** [comment] 2021-03-23 18:12
I think #736 might be related. @kblok Do you think it's possible that it's a race condition and not about "async all the way"?

**Comment by kblok** [comment] 2021-03-23 18:15
@Androbin where it's not async in your code?

**Comment by monterosr24** [comment] 2021-04-05 21:48
Does everyone know if have another way to resolve the problem, when we try to create a new page?
I tried to use this code but, I still have the same issue:
var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true,
                IgnoreHTTPSErrors = true,
                Args = new[] {
                    "--no-sandbox",
                    "--disable-infobars",
                    "--disable-setuid-sandbox",
                    "--ignore-ICertificatePolicy-errors",
                    },
            });
var page = await browser.NewPageAsync().ConfigureAwait(false);

**Comment by Androbin** [comment] 2021-04-05 23:58
Can reproduce reliably:
```csharp
using System.Threading;
using System.Threading.Tasks;

using PuppeteerSharp;

public class Program
{
    public static async Task Main()
    {
        await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultChromiumRevision).ConfigureAwait(false);
        using var browser = await Puppeteer.LaunchAsync(new LaunchOptions
        {
            Headless = true,
        }).ConfigureAwait(false);

        // Variant A
        Task.Run(() => browser.NewPageAsync()).Wait();

        // Variant B
        var tcs = new TaskCompletionSource<Page>(TaskCreationOptions.RunContinuationsAsynchronously);
        var timer = new Timer(async _ => tcs.SetResult(await browser.NewPageAsync().ConfigureAwait(false)));
        await tcs.Task.ConfigureAwait(false);
    }
}
```
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PuppeteerSharp" Version="3.0.0" />
  </ItemGroup>
</Project>
```

**Comment by kblok** [comment] 2021-04-06 00:36
@Androbin Did you try with the `EnqueueAsyncMessages` flag?

**Comment by Androbin** [comment] 2021-04-06 00:38
Same with `EnqueueAsyncMessages = true`

**Comment by Androbin** [comment] 2021-04-06 01:09
I just tested with `master` and the issue is gone, since `28436ad2516d489a98fbdae939773794cf503594` to be precise.

**Comment by monterosr24** [comment] 2021-04-06 01:52
@Androbin Do you know when the code is published in the nugget?

**Comment by Androbin** [comment] 2021-04-06 01:53
@kblok will know

**Comment by Androbin** [comment] 2021-04-08 03:26
@kblok Once 28436ad2516d489a98fbdae939773794cf503594 is released, I think this issue can be closed.

**Comment by kblok** [comment] 2021-04-09 12:12
@Androbin can you test with master branch and tell me if we can close this?

**Comment by Androbin** [comment] 2021-04-10 05:41
@kblok Every version since 28436ad2516d489a98fbdae939773794cf503594 passes the test script, most recently 02c0599a7e16774ab8b56df6cb1ce7504a50d5bc. I say we can close this issue, and I would suggest we make a minor release first.

**Closed** 2021-07-03 20:49 UTC
Labels: help wanted

**Comment by koryphaee** [comment] 2021-07-24 12:12
I have this issue again in version 5.0.0. I am running Puppeteer Sharp in a Linux Docker container.
The issue does not occur when I directly on Windows 10.

**Comment by CarlosResendiz** [comment] 2022-01-18 20:47
> Can you post the log? [See this article.](https://github.com/kblok/puppeteer-sharp/blob/master/docfx_project/examples/LodCDP.md)

this article link is broken

**Comment by Androbin** [comment] 2022-01-18 21:35
@CarlosResendiz [LogCDPCommunication.md](https://github.com/hardkoded/puppeteer-sharp/blob/master/docfx_project/examples/LogCDPCommunication.md)

**Comment by PhotoAtomic** [comment] 2023-04-06 06:19
just deleting the folder where chromium was automatically downloaded by the fetcher,  and let it run again, solved my issue. probably the first time something bad happened and the download was corrupted? maybe.
