### ISSUE TITLE
Protocol error(Runtime.callFunctionOn): Target closed. 

### ISSUE THREAD

**Issue by kerohero** [hardkoded/puppeteer-sharp#1505] opened 2020-06-23 07:06 UTC
### Description

It happens only if you're using Proxies, after logging in, when the page redirects you. You get the error, I can't share the website or the code :( 
When the error occurs, the page is still open, it's not closed.

### Full Error

`Protocol error(Runtime.callFunctionOn): Target closed. (NetworkManager failed to process Fetch.requestPaused. Value cannot be null.
Parameter name: key.    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at PuppeteerSharp.Helpers.MultiMap`2.Add(TKey key, TValue value)
   at PuppeteerSharp.Helpers.AsyncDictionaryHelper`2.<GetItemAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.NetworkManager.<OnRequestAsync>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.NetworkManager.<OnRequestPausedAsync>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.NetworkManager.<Client_MessageReceived>d__40.MoveNext())`

### Expected behavior:

Redirects just fine without the error occurring

### Actual behavior:

That error occurs 

### Versions

Latest (2.0.3)

**Comment by kblok** [comment] 2020-06-23 11:23
It will be hard to reproduce without an example...
Can you build an example with a public site?

**Comment by kerohero** [comment] 2020-06-25 09:23
@kblok  Tried to reproduce it with other websites, wasn't lucky enough. 
I can download PuppeteerSharp and debug it for you, just lemme know what to debug,
I was checking the function 'OnRequestPausedAsync' and the NetworkManager in general, there is 3 ConcurrentDictionary, the code tries to add a value with a null key to one of them, Shouldn't checking if the key is null or not solve the problem? 
Sorry for my late reply.

**Comment by kblok** [comment] 2020-06-25 15:18
What I tend to do is running the same code in puppeteer-sharp and in puppeteer. And see, first if the code works in pptr and if it does I see what is failing on pptr#

**Comment by Solaflex** [comment] 2020-07-08 13:17
I have the same issue since recent time. I am not aware of changing something which could lead to this issue. I use browserless and Chrome. The code is using the lastest puppeteer-sharp version (2.0.3)

Please use this code to reproduce the issue. I can provide you credentials to luminati.io if you need. Please drop me a private message if so.

`
try
{

	using (var browser = await Puppeteer.ConnectAsync(new ConnectOptions()
	{
		BrowserWSEndpoint = "wss://chrome.browserless.io?--proxy-server=proxyurl"
	}))
	{

		var page = await browser.NewPageAsync();
		await page.AuthenticateAsync(new Credentials()
		{
			Username = "proxyusername",
			Password = "proxypassword"
		});
		await page.GoToAsync("https://www.spotify.com/signup");
		await page.WaitForSelectorAsync("#email");
		await page.TypeAsync("#email", "test@email.com");

	}

}
catch (Exception ex)
{
	string error = ex.Message;
}
`

> "Protocol error(DOM.resolveNode): Target closed. (NetworkManager failed to process Fetch.requestPaused. Value cannot be null. (Parameter 'key').    at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNullException()\r\n   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)\r\n   at PuppeteerSharp.Helpers.MultiMap`2.Add(TKey key, TValue value)\r\n   at PuppeteerSharp.Helpers.AsyncDictionaryHelper`2.GetItemAsync(TKey key)\r\n   at PuppeteerSharp.NetworkManager.OnRequestAsync(RequestWillBeSentPayload e, String interceptionId)\r\n   at PuppeteerSharp.NetworkManager.OnRequestPausedAsync(FetchRequestPausedResponse e)\r\n   at PuppeteerSharp.NetworkManager.Client_MessageReceived(Object sender, MessageEventArgs e))"

**Comment by Solaflex** [comment] 2020-07-09 20:42
The code runs fine on pptr but fails on pptr# ...

**Comment by kerohero** [comment] 2020-07-13 23:32
@kblok @Solaflex So I downloaded Puppeteer Sharp code and added it to my project to debug it
The problem is in the NetworkManager file, the OnRequestAsync method, specifically in this line 
`var frame = await FrameManager.TryGetFrameAsync(e.FrameId).ConfigureAwait(false);`
e.FrameId being null causes the exception, I gone to check Puppeteer itself and found this 
`const frame = event.frameId
      ? this._frameManager.frame(event.frameId)
      : null;
`
As you can see the frame itself can be null so I adjusted the code to be 
`var frame = !string.IsNullOrEmpty(e.FrameId) ? await FrameManager.TryGetFrameAsync(e.FrameId).ConfigureAwait(false) : null;`
Works like a charm for me.

**Comment by kerohero** [comment] 2020-07-13 23:33
@Solaflex If you can confirm that this works for you too, I can make a PR

**Comment by Solaflex** [comment] 2020-07-14 10:01
@kerohero 
I can confirm that your new line has fixed the issue. A PR would be great.

**Comment by kblok** [comment] 2020-07-15 12:01
@kerohero PRs are welcome :)

**Comment by kerohero** [comment] 2020-07-16 05:57
Created the PR, Idk if I did it right, it's my first time XD

**Comment by kblok** [comment] 2020-07-16 11:02
Fixed on #1521 thank you @kerohero! I hope this is the first PR of many to come!

**Closed by kblok** 2020-07-16 11:02 UTC
Labels: bug

**Comment by mcopur** [comment] 2020-07-16 13:01
@kblok @kerohero @Solaflex 
Just a quick note, there is a problem between puppeteersharp and the latest version of Chrome. That error occurs, if you try to go for example kijk.nl and if you try to get buttons on the page. When I uninstall the latest version of Chrome and installed Chrome  Version 79.0.3945.88, it worked without any issue. You might want to check it.

**Comment by kblok** [comment] 2020-07-16 13:04
@mcopur the browser failing is the browser downloaded by puppeteer sharp or you are using `ExecutablePath` to use the installed browser?

**Comment by mcopur** [comment] 2020-07-16 14:03
@kblok  I am using ExecutablePath, already installed by the user on windows 10. It is not Chromium, it is Chrome.

**Comment by kblok** [comment] 2020-07-16 14:06
@mcopur there is a mapping stating which puppeteer/pptr# version works with which Chrome(ium) version [here](https://github.com/puppeteer/puppeteer/blob/v5.1.0/docs/api.md)

**Comment by mcopur** [comment] 2020-07-16 14:15
@kblok I was using puppeteer-sharp directly not the puppeteer. Is there a configuration to change it in puppeteer-sharp, or do I need to install it? Currently, I am using the pupperteer-sharp latest version which is 2.0.3
If I am not mistaken, Puppeteer-sharp uses puppeteer behind the scene, but I don't know how to change puppeteer version for puppeteer-sharp. If there is a way please let me know

**Comment by kblok** [comment] 2020-07-16 14:17
@mcopur the mapping is the same as puppeteer. Puppeteer-Sharp doesn't use puppeteer under the hood. But as each version might use different Chromium APIs, so it needs a specific Chromium version in order to work. You could try using another version, but that's not guaranteed.

**Comment by kerohero** [comment] 2020-07-29 22:26
@mcopur I'm aware of that issue, faced it myself and as you said rolling back to Chrome 78-79 solves it, that was enough for me. However my PR solves that issue too, you can run the latest Chrome just fine.
