### ISSUE TITLE
Failed to launch Base! 

### ISSUE THREAD

**Issue by vibhav107** [hardkoded/puppeteer-sharp#1684] opened 2021-04-01 21:53 UTC
I have implemented it in my local and works well. But when I moved the changes to window server it's giving below error 

```
Failed to launch Base! [0402/075840.212:ERROR:os_crypt_win.cc(70)] Failed to encrypt: The system cannot find the file specified.
 (0x2)\r\n[0402/075840.212:FATAL:headless_browser_main_parts.cc(103)] Check failed: OSCrypt::Init(local_state_.get()). 
\r\nBacktrace:\r\n\tIsSandboxedProcess [0x00007FFC31341842+705042]\r\n\tIsSandboxedProcess 
[0x00007FFC312C39A2+189298]\r\n\tIsSandboxedProcess [0x00007FFC312D2AF8+251080]\r\n\tIsSandboxedProcess 
[0x00007FFC312D39E0+254896]\r\n\tRelaunchChromeBrowserWithNewCommandLineIfNeeded 
[0x00007FFC32B12123+12980755]\r\n\tRelaunchChromeBrowserWithNewCommandLineIfNeeded 
[0x00007FFC32B11E8D+12980093]\r\n\tovly_debug_event [0x00007FFC2F905929+16331561]\r\n\tovly_debug_event 
[0x00007FFC2FCC5B17+20264215]\r\n\tovly_debug_event [0x00007FFC2F904675+16326773]\r\n\tovly_debug_event 
[0x00007FFC2F9073BE+16338366]\r\n\tIsSandboxedProcess [0x00007FFC31DB7DB7+11675527]\r
\n\tCrashForExceptionInNonABICompliantCodeRange [0x00007FFC3125A837+8179991]\r
\n\tCrashForExceptionInNonABICompliantCodeRange [0x00007FFC3125B5AD+8183437]\r
\n\tCrashForExceptionInNonABICompliantCodeRange [0x00007FFC3125B20C+8182508]\r
\n\tCrashForExceptionInNonABICompliantCodeRange [0x00007FFC3125A1BD+8178333]\r
\n\tCrashForExceptionInNonABICompliantCodeRange [0x00007FFC3125A53A+8179226]\r
\n\tCrashForExceptionInNonABICompliantCodeRange [0x00007FFC31294D1A+8418810]\r
\n\tCrashForExceptionInNonABICompliantCodeRange [0x00007FFC31294BDC+8418492]\r
\n\tCrashForExceptionInNonABICompliantCodeRange [0x00007FFC312949E7+8417991]\r\n\tChromeMain 
[0x00007FFC2E971238+408]\r\n\tOrdinal0 [0x00007FF6E8CF26B8+9912]\r\n\tOrdinal0 [0x00007FF6E8CF1A41+6721]\r
\n\tGetHandleVerifier [0x00007FF6E8E3AF42+904642]\r\n\tBaseThreadInitThunk [0x00007FFC68F113F2+34]\r
\n\tRtlUserThreadStart [0x00007FFC6AB054F4+52]\r\n\r\n
```

Can anyone please advice what should be the fix for above error message?

**Comment by kblok** [comment] 2021-04-04 14:53
closing in favor of the StackOverflow question https://stackoverflow.com/questions/66921026/puppeteer-sharp-failed-to-launch-base

**Closed by kblok** 2021-04-04 14:53 UTC

**Comment by shindmay** [comment] 2022-08-04 18:37
I was recently updating the puppeteer from 1.x to the latest, one version by another.
Observations:

- This issue arises in 6.0.0 and consists till 7.0.0
- The chrome version was 103.x
- When upgraded to 8.0.0 I also updated Chrome to the latest 104.x

The issue is no more for me.
